### ISSUE TITLE
Connection string issue - Password cannot contain word 'Server'. 

### ISSUE THREAD

**Issue by mschahal** [rvegajr/ez-api-urf-net#2]
If password field has word Server in it, the code gen treats the connection string differently.

**Comment by mschahal** [comment]
It also doesn't like special characters '$' in the password.

**Comment by rvegajr** [comment]
the issue was with EzDbCodeGen.  It needed to be updated to parse things correctly.  This has been pushed to Nuget and the change to this project should have corrected this.  thanks again for reporting this!
